# Generated by Django 5.1.4 on 2024-12-17 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام برند')),
                ('brand_country', models.CharField(max_length=20, verbose_name='کشور برند')),
                ('url_title', models.SlugField(unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100, verbose_name='رنگ')),
                ('color_code', models.CharField(max_length=30, verbose_name='کد رنگ')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='مدل گوشی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('display_size', models.PositiveIntegerField(verbose_name='سایز صفحه نمایش')),
                ('built_country', models.CharField(max_length=50, verbose_name='کشور سازنده')),
                ('is_exist', models.BooleanField(verbose_name='موجود / ناموجود')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.brand', verbose_name='برند محصول')),
                ('color', models.ManyToManyField(to='product_module.productcolor', verbose_name='رنگ محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
