# Generated by Django 5.1.4 on 2024-12-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_remove_product_color_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True, verbose_name='کشور سازنده')),
                ('url_title', models.SlugField(unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'کشور سازنده',
                'verbose_name_plural': 'کشورهای سازنده',
            },
        ),
        migrations.RenameField(
            model_name='productcolor',
            old_name='color_name',
            new_name='name',
        ),
    ]
