# Generated by Django 5.1.4 on 2024-12-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_alter_product_built_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color_code',
            field=models.CharField(max_length=30, unique=True, verbose_name='کد رنگ'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='رنگ'),
        ),
    ]
